export const initData = {
  paperId: [
    { key: "examName", value: undefined },
    { key: "totalScore", value: undefined },
    { key: "evaluationCourseId", value: undefined },
    { key: "gradeIdList", value: [] },
    { key: "subjectId", value: undefined },
    { key: "courseIdList", value: [] },
    { key: "groupIdList", value: [] },
    { key: "evaluationCategoryId", value: undefined },
    { key: "childEvaluationCategoryId", value: undefined },
    { key: "weights", value: undefined },
    { key: "evaluationItemId", value: undefined },
    { key: "total", value: undefined },
    { key: "evaluationCriterionId", value: undefined },
  ],
  gradeIdList: [
    { key: "subjectId", value: undefined },
    { key: "evaluationCourseId", value: undefined },
    { key: "courseIdList", value: [] },
    { key: "groupIdList", value: [] },
    { key: "evaluationCategoryId", value: undefined },
    { key: "childEvaluationCategoryId", value: undefined },
    { key: "weights", value: undefined },
    { key: "evaluationItemId", value: undefined },
    // { key: 'total', value: undefined },
    { key: "evaluationCriterionId", value: undefined },
  ],
  subjectId: [
    { key: "courseIdList", value: [] },
    { key: "groupIdList", value: [] },
    { key: "evaluationCourseId", value: undefined },
    { key: "evaluationCategoryId", value: undefined },
    { key: "childEvaluationCategoryId", value: undefined },
    { key: "weights", value: undefined },
    { key: "evaluationItemId", value: undefined },
    // { key: 'total', value: undefined },
    { key: "evaluationCriterionId", value: undefined },
  ],
  courseIdList: [{ key: "groupIdList", value: [] }],
  evaluationCourseId: [
    { key: "evaluationCategoryId", value: undefined },
    { key: "childEvaluationCategoryId", value: undefined },
    { key: "weights", value: undefined },
    { key: "evaluationItemId", value: undefined },
    // { key: 'total', value: undefined },
    { key: "evaluationCriterionId", value: undefined },
  ],
  evaluationCategoryId: [
    { key: "childEvaluationCategoryId", value: undefined },
    { key: "weights", value: undefined },
    { key: "evaluationItemId", value: undefined },
    // { key: 'total', value: undefined },
    { key: "evaluationCriterionId", value: undefined },
  ],
  childEvaluationCategoryId: [
    { key: "weights", value: undefined },
    { key: "evaluationItemId", value: undefined },
    // { key: 'total', value: undefined },
    { key: "evaluationCriterionId", value: undefined },
  ],
  evaluationItemId: [
    // { key: 'total', value: undefined },
    { key: "evaluationCriterionId", value: undefined },
  ],
};
